name: Release

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0 or 1.0.0)"
        required: true
        default: "1.0.0"
      platform:
        description: "Build platform"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - windows
          - mac
          - linux
permissions:
  contents: write
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Get release tag
        id: get-tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js and Electron
        env:
          BUILD_TARGET: electron  # 在这里统一设置
          MODEL_PROVIDER_URL: "xx.xx.xx.xx"
          MODEL_PROVIDER_API_KEY: "xx.xx.xx.xx"
        run: pnpm electron:build

      - name: Pack for Mac
        if: matrix.os == 'macos-latest'
        run: pnpm electron:pack:mac
        env:
          BUILD_TARGET: electron  # 在这里统一设置
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Pack for Windows
      #   if: matrix.os == 'windows-latest'
      #   run: pnpm exec electron-builder --win --config electron-builder.yml
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 发布
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          makeLatest: false
          skipIfReleaseExists: true
          tag: ${{ steps.get-tag.outputs.tag }}
          artifacts: "release/*.exe,release/*.zip,release/*.dmg,release/*.AppImage,release/*.snap,release/*.deb,release/*.rpm,release/*.tar.gz,release/latest*.yml,release/rc*.yml,release/beta*.yml,release/*.blockmap"
          token: ${{ secrets.GITHUB_TOKEN }}
